export type FunnelTag = 'Lead Capture' | 'Booking' | 'Checkout' | 'Website'

export type Funnel = {
  file: string
  label: string
  tag: FunnelTag
  desc: string
  /** Public subfolder the HTML + thumbnail live under. Default 'funnels'. */
  dir?: 'funnels' | 'samples'
}

/**
 * Your funnel pages and website samples. Every entry is a PLACEHOLDER page
 * generated by scripts/make-placeholder-sites.mjs.
 *
 * To add your own: drop the page's HTML in public/funnels/ (single pages) or
 * public/samples/ (full websites), add an entry here, then run
 * `node scripts/make-thumbs.mjs` to render its thumbnails.
 */

export const gymFunnel: Funnel[] = []

export const bookingFunnel: Funnel[] = []

export const websiteFunnel: Funnel[] = [
  {
    file: 'indiewebsite.html',
    label: 'Indie Book Festival',
    tag: 'Website',
    desc: 'A website design project for a book convention.',
    dir: 'samples',
  },
]

/**
 * Tag -> color map. Brand-external colors that identify the page type, passed
 * to CSS via an inline --tag-color custom property.
 */
export const tagColors: Record<FunnelTag, string> = {
  'Lead Capture': '#8b5cf6',
  Booking: '#ec4899',
  Checkout: '#f59e0b',
  Website: '#FF7A1A',
}
